### ISSUE TITLE
Generate Svgo action is failing

### ISSUE THREAD

**Issue by jizc** [OlivierLDff/MaterialDesignSvgo#2]
The [Generate Svgo](https://github.com/OlivierLDff/MaterialDesignSvgo/actions/workflows/generate-svgo.yml) action has been failing since the end of October 2022.

This repo has been great for getting more optimized icons, and I would love to see it stay updated 😃

**Comment by jizc** [comment]
I ended up making a fork to fix the workflow. The cause of the problem is this commit: https://github.com/svg/svgo/commit/6295c60fbfcc8325bf8c089ecd27cad7e5567f3d

**Comment by OlivierLDff** [comment]
I haven't seen your issue!
Would you mind creating a PR? I should rename main branch to `main`

**Comment by jizc** [comment]
No problem, I see the workflow is fixed 🎉 Closing this.

**Comment by OlivierLDff** [comment]
Yes thanks for the fix!
