### ISSUE TITLE
GitHub action has been disabled

### ISSUE THREAD

**Issue by jizc** [OlivierLDff/MaterialDesignSvgo#3]
The [Generate Svgo](https://github.com/OlivierLDff/MaterialDesignSvgo/actions/workflows/generate-svgo.yml) action has been disabled due to inactivity, so the newest icons have not synced.
> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

**Comment by OlivierLDff** [comment]
Thank you for the feedback, I re enabled it
